# Migrated from assets/configs/meanGRU/all_shared.yaml
model_name: meanGRU
module: meanGRU
single_embedder: true
single_GRU: true
single_predictor: true
rnn:
  input_embedding_size: 16
  hidden_size: 32
  num_layers: 1
  dropout: 0.0
loss:
  prediction_delay: 0
  prediction_depth: 1
  forecast_weight: 1.0
lr: 0.001
